// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVnlLUZLUf2nRsO63rGF9SpiiVDlyJGtM',
    appId: '1:629463208378:web:35fb897782f66f286e4d83',
    messagingSenderId: '629463208378',
    projectId: 'social-app-2bb69',
    authDomain: 'social-app-2bb69.firebaseapp.com',
    storageBucket: 'social-app-2bb69.appspot.com',
    measurementId: 'G-4GSHWNMT0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdX-8BvJ1hRX4flz9UQYS1I6LSybZGXXk',
    appId: '1:629463208378:android:752d0896f8299b2a6e4d83',
    messagingSenderId: '629463208378',
    projectId: 'social-app-2bb69',
    storageBucket: 'social-app-2bb69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSOYnzHYHGDRIaJm3WJXjKc4yy1ilZCnI',
    appId: '1:629463208378:ios:a7f5830a269eda3a6e4d83',
    messagingSenderId: '629463208378',
    projectId: 'social-app-2bb69',
    storageBucket: 'social-app-2bb69.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSOYnzHYHGDRIaJm3WJXjKc4yy1ilZCnI',
    appId: '1:629463208378:ios:a7f5830a269eda3a6e4d83',
    messagingSenderId: '629463208378',
    projectId: 'social-app-2bb69',
    storageBucket: 'social-app-2bb69.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVnlLUZLUf2nRsO63rGF9SpiiVDlyJGtM',
    appId: '1:629463208378:web:c68545155c41e2f76e4d83',
    messagingSenderId: '629463208378',
    projectId: 'social-app-2bb69',
    authDomain: 'social-app-2bb69.firebaseapp.com',
    storageBucket: 'social-app-2bb69.appspot.com',
    measurementId: 'G-41WKKW1KFQ',
  );
}
